### ISSUE TITLE
How to apply Getty Images Api key. I can't find the application entrance.

### ISSUE THREAD

**Issue by gxulmh** [gettyimages/gettyimages-api_dotnet#14]

**Comment by gxulmh** [comment]
How to apply Getty Images Api key.
I can't find the application entrance.

**Comment by mapitman** [comment]
Take a look at the [README](https://github.com/gettyimages/gettyimages-api_dotnet/blob/master/README.md), there are examples. If that doesn't help, please respond with more details about what you're trying to do and what you've tried so far.

**Comment by mapitman** [comment]
I think I may have misunderstood your question. If you would like to get an API key, please contact apisupport@gettyimages.com.

**Comment by gxulmh** [comment]
Yes,i want to get an API key.Thank you very much
