### ISSUE TITLE
ToLowerInvariant

### ISSUE THREAD

**Issue by rekrah** [gettyimages/gettyimages-api_dotnet#15]
Somewhere in the code, ToLowerInvariant() is messing up an Image.WithIds() request, try id BA19430.

![image](https://cloud.githubusercontent.com/assets/5775607/9012526/9b32bfb2-3783-11e5-9a7e-3b9a76a70ea5.png)

![image](https://cloud.githubusercontent.com/assets/5775607/9012805/b842b2f4-3785-11e5-9288-65923fdf63d6.png)

Here's the Json response from the GettyImages API... The C# SDK made BA19430 lowercase before it sent it to the Getty and hence they responded with "image not found".

{
"images": [
{
"id": "150067270",
"display_sizes": [
{
"is_watermarked": false,
"name": "thumb",
"uri": "http://cache1.asset-cache.net/xt/150067270.jpg?v=1&g=fs1|0|FKM|67|270&s=1&b=RjI4"
}
],
"title": "Spinner dolphins"
},
{
"id": "155156342",
"display_sizes": [
{
"is_watermarked": false,
"name": "thumb",
"uri": "http://cache1.asset-cache.net/xt/155156342.jpg?v=1&g=fs1|0|FKO|56|342&s=1&b=RjI4"
}
],
"title": "Primer plano delfin"
}
],
"images_not_found": [
"ba19430"
]
}

I'd try doing a pull request and fixing it but I'm afraid I might make things worse or spend way to many hours working out how to unit test to ensure I didn't.  Hoping someone who's more familiar with the code and the GitHub process will make this happen for everyone.  Thanks!

**Comment by rekrah** [comment]
Here's the Json response from the GettyImages API...  The C# SDK made BA19430 lowercase before it sent it to the Getty and hence they responded with "image not found".

{
  "images": [
    {
      "id": "150067270",
      "display_sizes": [
        {
          "is_watermarked": false,
          "name": "thumb",
          "uri": "http://cache1.asset-cache.net/xt/150067270.jpg?v=1&g=fs1|0|FKM|67|270&s=1&b=RjI4"
        }
      ],
      "title": "Spinner dolphins"
    },
    {
      "id": "155156342",
      "display_sizes": [
        {
          "is_watermarked": false,
          "name": "thumb",
          "uri": "http://cache1.asset-cache.net/xt/155156342.jpg?v=1&g=fs1|0|FKO|56|342&s=1&b=RjI4"
        }
      ],
      "title": "Primer plano delfin"
    }
  ],
  "images_not_found": [
    "ba19430"
  ]
}
    base: {
  "images": [
    {
      "id": "150067270",
      "display_sizes": [
        {
          "is_watermarked": false,
          "name": "thumb",
          "uri": "http://cache1.asset-cache.net/xt/150067270.jpg?v=1&g=fs1|0|FKM|67|270&s=1&b=RjI4"
        }
      ],
      "title": "Spinner dolphins"
    },
    {
      "id": "155156342",
      "display_sizes": [
        {
          "is_watermarked": false,
          "name": "thumb",
          "uri": "http://cache1.asset-cache.net/xt/155156342.jpg?v=1&g=fs1|0|FKO|56|342&s=1&b=RjI4"
        }
      ],
      "title": "Primer plano delfin"
    }
  ],
  "images_not_found": [
    "ba19430"
  ]
}

**Comment by mapitman** [comment]
Hi, I work on the Getty Images API team. I'll Take a look at this today and see if I can get a fix for you.

**Comment by rekrah** [comment]
Thanks Mark.  While you're at it, it appears that if you send in more than 166 id's the exception changes from "This operation only supports requests of one or more resources, but cannot exceed 100.  Resources requested: 166" to "Error reading JObject from JsonReader. Path '', line 0, position 0.".  Much lower priority since it's an exception nonetheless but I'm sure you'd agree, it's little missleading.  Here's 177 id's, excluding BA19430 :-)...

List<string> Ids = new List<string>() { "133284650","165563099","164976960","145590709","159614981","167866647","161675287","144669971","166520306","85388827","123244845","154874419","164211321","165564339","159628465","159543078","139967162","140194173","146015165","79326155","148967321","137727603","159737117","79326537","109393787","97373079","127737931","171758464","163257283","173180018","sb10061939h-001","166229327","sb10061939f-002","83454812","167360837","178351969","165017045","149263578","128078542","150067270","151083146","155156342","110886461","96208641","165025616","136643000","142091026","171449296","166226475","166998636","dv2131012","166239164","sb10068815b-001","200378416-001","177974845","145896170","177973889","166128405","122029651","131288011","82880704","140193805","150968717","142728411","160966210","140243027","160626308","142866339","141089646","150931243","144560213","142861425","147850748","154330733","163589602","140193808","141697024","153088941","103753169","159628904","165526703","137885832","130897936","135929814","165205388","136009446","110052619","85206765","86490035","146660513","171596791","144564048","53328986","145580458","144462915","147454923","149008344","150749857","148198811","145634220","sb10062076n-002","112175618","144561164","150516368","147205717","148198031","147205767","160931318","147205748","150653534","150973324","143992771","139078524","145068110","145065462","153929324","149317178","109231793","153936395","159122046","146701553","138342978","143780829","152892456","145555057","144448016","170943039","150415678","167766143","136234224","85866540","885857-001","144692259","142827576","149262920","150096644","162715854","164765752","164173804","171469251","148197885","145067938","148197883","144486906","200443040-001","110162733","121991200","98536476","88841639","143070717","171952367","149009954","150077446","sb10065029f-001","144561424","151895104","108137354","147192792","144560471","dv1897026","162179207","145135950","166825930","78367589","144564079","136493191","144011313" };

**Comment by rekrah** [comment]
It looks like the Getty Images API stops giving a nice message at 166, which is probably why the SDK does what it does also (although you probably knew that) - just an FYI.

**Comment by rekrah** [comment]
Any progress, Mark?

**Comment by mapitman** [comment]
Sorry, no. I looked at it but the fix was a little more involved than I had the time for. I'll try to get it prioritized with the rest of our current work.

**Comment by mapitman** [comment]
I will update the nuget package later today.
