### ISSUE TITLE
WithEditorialSegment() seems to have no effects

### ISSUE THREAD

**Issue by jackmor** [gettyimages/gettyimages-api_dotnet#16]
Hi, I'm trying without success to search images within a specific editorial segment.

The code I'm trying to use is something like:
var searchResult = await client.Search()
    .Images()
    .Editorial()
    .WithEditorialSegment(XXX)
    .WithPhrase("test")
    .WithSortOrder("newest")
    .ExecuteAsync();

Where XXX is a valid EditorialSegment flag. The problem is that it doesn't search within the specified EditorialSegment at all, looking instead through all the editorial images available.

Looking at the code, it seems to me that something may be missing: I see a protected variable EditorialSegments inside SearchImages, but I can't find the place where it's applied as a filter.

Anyway, thanks for the good library ;)

**Comment by CaseyMacPherson** [comment]
jackmor,

I've submitted a Pull Request with your issue fixed. Thanks for the details :)

**Comment by CaseyMacPherson** [comment]
This should be fixed, reopen if it doesn't work for you.

Casey MacPherson
Senior Software Engineer
Getty Images API
https://api.gettyimages.com

**Comment by jackmor** [comment]
It works like a charm!
Thanks a lot, you were really fast :)
