### ISSUE TITLE
Get a image content stream

### ISSUE THREAD

**Issue by amatiasq** [gettyimages/gettyimages-api_dotnet#21]
I'm trying to download an image with this snippet

```csharp
var result = getty.Download()
  .Image()
  .WithId(Request.Query.id)
  .ExecuteAsync()
  .Result;
```

But I'm getting the error message

> No MediaTypeFormatter is available to read an object of type 'Object' from content with media type 'application/x-download'.

I'm not sure what this means but I end up [at this line](https://github.com/gettyimages/gettyimages-api_dotnet/blob/master/GettyImages.Api/WebHelper.cs#L102) where what I was expecting is something like `.ReadAsStream()`.

**Comment by mapitman** [comment]
Looks like a bug. The default behavior in the SDK should be AutoDownload = false, but that doesn't seem to be the case. As a workaround, you can do this:
```
var result = getty.Download()
  .Image()
  .WithId(Request.Query.id)
  .WithAutoDownload(false)
  .ExecuteAsync()
  .Result;
```

Then you can get the download URI:
```
var downloadUri = result.uri;
```

**Comment by mapitman** [comment]
Removed auto download from SDK as it was not really useful. 
[Nuget](https://www.nuget.org/packages/GettyImages.Api/)
[Release 3.0.0.0](https://github.com/gettyimages/gettyimages-api_dotnet/releases/tag/3.0.0.0)
