### ISSUE TITLE
Just Loops

### ISSUE THREAD

**Issue by sdkibb** [gettyimages/gettyimages-api_dotnet#23]
Used with example code and it does not work. It just hangs. Is there any documentation on how to use the SDK? It's not on Github or anywhere else on the net that I can find.

**Comment by mapitman** [comment]
I've created a sample project [here](https://github.com/gettyimages/gettyimages-api_dotnet_sample). Clone it, add your key and secret to environment variables and try it out. It should search for monkeys and dump out the response to the console.

**Comment by sdkibb** [comment]
Thanks. 

 I cloned it but GettyImages and Newtonsoft cannot be found even after retrieving from NuGet It's also not a console project.

**Comment by mapitman** [comment]
Are you using VS 2015?

**Comment by sdkibb** [comment]
Yes, I also get The type 'Task<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Working through it but the project doesn't work as is.

**Comment by mapitman** [comment]
Weird, all I did was 
1. File | New | Project | Windows | Console Application
2. Add the GettyImages-Api nuget package
3. Add code to Main() in Program.cs

**Comment by mapitman** [comment]
By the way, the sample project is targeting .NET Framework 4.5.2

**Comment by sdkibb** [comment]
Yes, made sure that was set.

 To try it out I did - New Website -> NuGet the GettyImages.API -> Created default page -> Paste code in -> run page -> gives this error:

The type 'Task<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by sdkibb** [comment]
Ok, I added to the above project's web.config:

 <add assembly="System.Threading.Tasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />

and it runs but it still hangs on the client search. This is the third windows box and separate network I've tried it on and getting the same results.

 As you did, I created a new stock console application, pasted the code in and it continuously loops through the same error:: 

An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

Additional information: One or more errors occurred.

 This is also on more than one machine. I created a small wrapper class for what I need to do the web calls and handle the token management and it worked fine. I'm hoping to get some free time to investigate what the issue is an contribute back to this shortly. Sorry for sending you issues with no solutions!

**Comment by mapitman** [comment]
Did you set your API key and secret in environment variables?

**Comment by mapitman** [comment]
Going to close this issue. If you continue to have difficulties you can either reopen the issue or contact us through [Gitter](https://gitter.im/gettyimages/gettyimages-api_dotnet), our [forums](http://developer.gettyimages.com/forum/topics/125149) or our [Contact Us](http://developer.gettyimages.com/contact/contact) page.
