### ISSUE TITLE
Looking for a method to get image by Asset ID

### ISSUE THREAD

**Issue by aberezovsky** [gettyimages/gettyimages-api_dotnet#30]
Hi team. Is there a method where you can retrieve image by Asset ID. I can’t seem to find it. I've been using the Getty API for many years, but I just stumbled on this new version of API and haven't been able to find that.  My old way of getting the data still works, but I thought I’d ask if you do have a method like this that I just missed. Thanks.

**Comment by mapitman** [comment]
The simplest example would be something like this:
```csharp
var client = ApiClient.GetApiClientWithClientCredentials("YOUR_API_KEY", "YOUR_API_SECRET");
var result = await client.Images()
    .WithId("IMAGE_ID")
    .ExecuteAsync();
```
There's also a `.WithResponseFields("FIELD_NAME")` method you can add to the chain if the default metadata returned doesn't give you what you want.

**Comment by aberezovsky** [comment]
Ah...there it is! Perfect. Thank you!
