### ISSUE TITLE
The GettyImages.Api assembly in the nuget package is not Strong-Name signed

### ISSUE THREAD

**Issue by guoyu-wang** [gettyimages/gettyimages-api_dotnet#37]
Our project requires the assemblies to have Strong-Name Signing, we will hit this error when compiling the project using GettyImages.API 8.0.0

```
CSC : error CS8002: Referenced assembly 'GettyImages.Api, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

For more information about the Strong-Name Signing, see
- https://docs.microsoft.com/en-us/archive/msdn-magazine/2006/july/clr-inside-out-using-strong-name-signatures
- https://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error

To resolve this is quite simple, 
- Will need a generated SNK (Strong Name Key)
- Add the SNK as a GitHub action secret
- In the build.yml workflow, need to save the secret to the SNK file
- Use the SNK file to sign the assembly in the build process

Can send PR if someone can generate and add the SNK as a GitHub action secret

**Comment by ChrisSimmons** [comment]
Hello @guoyu-wang!

We'll need to discuss this internally before to decide on whether to make the .NET SDK a strong-named assembly.  While it's not a heavy lift to implement, there are other considerations that come into play.

If you are a current Getty customer (or working with one) and this is blocking work for you right now, please reach out to your technical contact at Getty.

**Comment by ChrisSimmons** [comment]
The opinions so far are in favor of doing this although I'd like to have a consensus within the whole team before we officially make the change.  We should have that in the next couple of days.  If you think this is something you'd like to tackle in a PR, please feel free.  One thing we do know is we'd like to take the position that strong-naming is not for _security_ but for _identity_, as highlighted in [Microsoft's current documentation on SN](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named).  Given that, and the guidance in that article to "consider checking in the private key associated with an assembly to your source control system", as part of that PR, please feel free to generate a `*.snk` file and check it in.

**PS**: And if you cannot create the PR, no worries.  Assuming the decision is made to make this change, we'll get this queued up with our internal work.

**Comment by ChrisSimmons** [comment]
My apologies on the long-overdue response to this.  I'm in favor of this and will be posting some further citations supporting strong-naming on the PR itself.  This will still require review by the other team member but I'll commit to getting a final 👍 / 👎 on this within a few days.

**Comment by ChrisSimmons** [comment]
The consensus is to not do strong-naming.  If this is still a requirement for you I would ask that you contact your Getty sales/technical contact directly.
